name: build foss snapshot image
on: workflow_dispatch

jobs:
    build:
        name: build foss snapshot image
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Install packages
              run: |
                  sudo apt-get update && \
                  sudo apt-get install -y \
                      build-essential \
                      clang \
                      flex \
                      bison \
                      g++ \
                      gawk \
                      gcc-multilib \
                      g++-multilib \
                      gettext \
                      git \
                      libncurses-dev \
                      libssl-dev \
                      python3-setuptools \
                      rsync \
                      unzip \
                      zlib1g-dev \
                      file \
                      jq \
                      wget && \
                  sudo apt-get clean

            - name: Checkout
              uses: actions/checkout@v4
              with:
                ref: 'mx4300-foss'

            - name: Update feeds
              run:  scripts/feeds update -a && scripts/feeds install -a
            
            - name: Get script
              run:  |
                    wget https://github.com/arix00/openwrt-mx4300/blob/buildscript/release_foss.sh
                    wget https://raw.githubusercontent.com/arix00/openwrt-mx4300/refs/heads/buildscript/genconfig_foss.sh

            - name: Generate config
              run:  sh genconfig_foss.sh snapshot

            - name: Build firmware images
              run:  make -j$(($(nproc)+1)) world
            
            - name: Check build version
              run:  cat `find staging_dir -name banner`

            - name: Prepare release
              run:  sh release_foss.sh ${{ env.ver }}
