name: test build foss snapshot image
on: workflow_dispatch
env:
  MAIN_REPO:  "https://github.com/arix00/openwrt-mx4300.git"
  BRANCH: "mx4300-foss"
  SCRIPT: "buildscript"

jobs:
    build:
        name: build foss snapshot image
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Install packages
              run: |
                  sudo apt-get update && \
                  sudo apt-get install -y \
                      build-essential \
                      clang \
                      flex \
                      bison \
                      g++ \
                      gawk \
                      gcc-multilib \
                      g++-multilib \
                      gettext \
                      git \
                      libncurses-dev \
                      libssl-dev \
                      python3-setuptools \
                      rsync \
                      unzip \
                      zlib1g-dev \
                      file \
                      jq \
                      wget && \
                  sudo apt-get clean

            - name: Checkout
              run:  |
                    git clone $MAIN_REPO --branch ${BRANCH}
                    cd openwrt-mx4300
                    git checkout ${SCRIPT} -- setenv.sh genconfig_foss.sh release_foss.sh

            - name: Update feeds
              run:  scripts/feeds update -a && scripts/feeds install -a
            
            - name: Generate config
              run:  sh genconfig_foss.sh snapshot

            - name: Build firmware images
              run:  make -j$(($(nproc)+1)) world
            
            - name: Check build version
              run:  cat `find staging_dir -name banner`

            - name: Prepare release
              run:  sh release_foss.sh ${{ env.ver }}
